platform :ios, "9.0"
workspace       "LSYCarouselViewDemo"
project "LSYCarouselViewDemo.xcodeproj"



target "LSYCarouselViewDemo" do
project "LSYCarouselViewDemo.xcodeproj"
use_frameworks!

pod 'Masonry'
pod 'SDWebImage'

end

